---
title: Pretty Docs
timezone: UTC
collections:
  doc:
    title: Doc
    output: true
    permalink: "/:path.html"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: doc
  values:
    layout: doc
- scope:
    path: ''
    type: pages
  values:
    layout: doc
remote_theme: LeakyAbstractions/pretty-docs
url: https://angelicamariagranados-cyber.github.io
baseurl: "/pretty-docs"
description: Free Bootstrap theme for your project documentation
branding:
  icon:
    name: icon_documents_alt
  highlight: Pretty
  bold: Docs
markdown: kramdown
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true
owner:
  name: Guillermo Calvo
  twitter: gcalvo
  copyright:
    notice: Lorem Ipsum
    author: "[Guillermo Calvo](https://guillermo.in/)"
open_graph:
  title: Pretty Docs
  site_name: Pretty Docs
  description: Free Bootstrap theme for your project documentation
  locale: en_US
  image: "/assets/images/thumb.png"
twitter_cards:
  title: Pretty Docs
  description: Free Bootstrap theme for your project documentation
  creator: gcalvo
  card: summary_large_image
  image: "/assets/images/thumb.png"
share:
  facebook:
    class: fb-like
    action: like
    layout: button_count
    show-faces: false
    share: false
  twitter:
    via: gcalvo
    text: 
    title: Tweet
  github:
    repo: LeakyAbstractions/pretty-docs
    position: right
    color: red
google_analytics: UA-61670496-5
